### ISSUE TITLE
android path

### ISSUE THREAD

**Issue by lxny** [cmdr2/unity-remote-obj-loader#2]
I tried it in my android application, but it seems this URL file:///Users/someone/somepath/model.obj doesn't suit android path. Is it possible, I tried some tweaks, but I can't get it to work.

**Comment by cmdr2** [comment]
Hi, is /Users an actual directory on your Android device? What error do you get if you try a URL like file:///sdcard/Download/stuff.obj ?

**Comment by lxny** [comment]
Wow, thank you for the reply, :) I thought it will take some time. These are the paths that I tried:
1. /storage/external_SD/sofa.obj
2. ///storage/external_SD/sofa.obj
3. file:///storage/external_SD/sofa.obj
*None of these worked, the sofa.mtl is in the same directory where the sofa.obj resides.

I tried using these script http://wiki.unity3d.com/index.php?title=ObjImporter and used this path "/storage/external_SD/sofa.obj", and it worked, it's color pink though, because this script doesn't include some mesh rendering.

I tried your script and it works perfectly when I assign the path to my local directory here in my laptop.  Like "file:///Users/someone/somepath/model.obj", so I'm wondering is it possible to use your script in android.

The error is nothing appears, but my application doesn't crash, or get some pop out error messages, I'm not testing my app in android studio so I can't see the logs, because I'm just using the build & run in unity, but I will try it now and get some info.

Thanks :).

**Comment by lxny** [comment]
Oh sorry, I'm not testing my app in android studio so I can't see the logs, because I'm just using the build & run in unity, but I will try it now and get some info.

**Comment by cmdr2** [comment]
Hmm, in Unity's Build Settings, can you enable "Development mode" and "Enable Script Debugging", and then build?

And on your laptop's command line, you can look at the Android logs generated by your app using 'adb logcat -s Unity DEBUG'. You can check where adb is present on your laptop by looking at Unity's Android SDK location setting (I think it is in Unity Preferences.. clicking the "Unity" top menu on Mac).

Also, as a random thought, could it be just a permissions issue? Can you make sure that your AndroidManifest.xml in Unity's Plugins/Android folder has READ_EXTERNAL_STORAGE permission added to it?

Cheers

**Comment by lxny** [comment]
Oh okay, thanks for the info. :), I will try it.

**Comment by cmdr2** [comment]
Closing, please let me know if the suggestion didn't fix the problem.
