### ISSUE TITLE
Asynchronous Importer and run-time Loader for Unity

### ISSUE THREAD

**Issue by gpvigano** [cmdr2/unity-remote-obj-loader#3]
Thank you for sharing your project (thanks also to the other contributors).

I'm writing here because I started a similar project ([AsImpL](https://github.com/gpvigano/AsImpL)) and I hope that someone, like you or everyone else interested in my work, will use, test and maybe improve what I have done (any contribution or feedback is welcome).

I found your project and other OBJ loaders very useful, but I decided to create my own project because I need to:
* load models in an asynchronous way (without "freezing" the scene during loading)
* load more models concurrently
* show the loading progress on a UI
* import the loaded models as assets into Unity projects
* prepare the loader to be extended with different file formats

These requirements to me seemed to be enough to start a new different project, instead of applying changes one of the available OBJ loaders.

I also worked on materials importing to improve the appearance of my 3D models:
* bump map
  * bump map is converted into a normal map
  * computation of normal maps and tangents
* specular map
  * specular map is converted to glossness map (metallic texture)
* reflection map
  * reflection map is replaced with the ambient reflection
    (skybox or reflection probes, if available)
* opacity map
    * diffuse and opacity maps are blended together in the albedo texture
* flag to use an Unlit shader for materials with the lighting rendered to the diffuse texture
Some options are available for vertices pre-scaling and vertical axis conversion.

On GitHub you can find my project: [AsImpL](https://github.com/gpvigano/AsImpL).
I tried to clearly mark contributions both in the source code and in the documentation. If you notice that something is missing please let me know and provide the needed information (authors, links, etc.), I will update my project as soon as possible.

[![image](https://raw.githubusercontent.com/gpvigano/AsImpL/master/images/test_AsImpL.jpg)](https://github.com/gpvigano/AsImpL)

**Comment by cmdr2** [comment]
Good luck with the project! :-)

BTW this project does asynchronous loading too, so I'm curious if it did not work as expected. There are specific steps to prevent freezing the main thread while loading and parsing:

https://github.com/cmdr2/unity-remote-obj-loader/blob/master/OBJ/src/OBJ.cs#L80
https://github.com/cmdr2/unity-remote-obj-loader/blob/master/OBJ/src/OBJ.cs#L265
https://github.com/cmdr2/unity-remote-obj-loader/blob/master/OBJ/src/OBJ.cs#L196

**Comment by gpvigano** [comment]
Yes, I am sorry! In fact I got this idea from you...

I was thinking about other OBJ loaders when I wrote that statement.

Anyway thank you very much for your reply, I added this row to the [README.md](https://github.com/gpvigano/AsImpL/blob/master/README.md):

> The first asynchronous loading implementation comes from [unity-remote-obj-loader](https://github.com/cmdr2/unity-remote-obj-loader).

**Comment by cmdr2** [comment]
No problem, that's alright :-) Thanks, and good luck! Your project looks very interesting, will try it out the next time I need to fetch OBJ files.
